version: '3.2'

services:

  redmine:
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: "no"
    ports:
      - "8080:3000"
    volumes:
      # - type: bind
      #   source: c:/temp/redmine-source-container/redmine
      #   target: /usr/src/redmine/
      - type: volume
        source: myredmine
        target: /usr/src/redmine
    links:
      - database
    environment:
      REDMINE_DB_MYSQL: database
      RAILS_ENV: 'development'
    stdin_open: true
    tty: true
    entrypoint:
      - rails
      - server
      - -b
      - 0.0.0.0

  database:
    image: mysql:5.7
    restart: "no"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: redmine_development

  samba:
    image: dperson/samba
    volumes:
      - type: volume
        source: myredmine
        target: /usr/src/redmine
    network_mode: "host"
    command: -u "redmine;1234;999;redmine" -s "redmine;/usr/src/redmine;yes;no;no" -g "force user = " -g "force group = " -g "create mask = 0000" -g "force create mode = 600" 
    depends_on:
      - redmine

volumes:
  myredmine: